openapi: '3.0.3'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
servers:
  - url: 'http://localhost:9090/api'
tags:
  - name: ice-creams
    description: Gestion des glaces
  - name: origins
    description: Gestion des origines des différents types de glace
  - name: containers
    description: Gestion des containers pour la glace
paths:
  /ice-creams:
    get:
      tags:
        - ice-creams
      summary: Obtient une liste de toutes les glaces
      operationId: getIceCreams
      parameters:
        - in: query
          name: price
          description: prix de la glace
          schema:
            type: number
            format: float
          required: false
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IceCreamDTOobj'
    post:
      tags:
        - ice-creams
      summary: Ajoute une nouvelle glace
      operationId: addIceCream
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/IceCreamDTOid'
      responses:
        '201':
          description: Glace créée
          headers:
            Location:
              description: URL de la glace créée
              schema:
                type: string
                format: uri
        '400':
          description: La glace n'a pas pu être créée, il manque des champs obligatoires
        '422':
          description: La glace n'a pas pu être créée, un champ est invalide
    put:
      tags:
        - ice-creams
      summary: Modifer ou ajouter une glace
      operationId: updateCreateIceCream
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/IceCreamDTOid'
      responses:
        '200':
          description: Glace modifiée
          headers:
            Location:
              description: URL de la glace modifiée
              schema:
                type: string
                format: uri
        '201':
          description: Glace créée
          headers:
            Location:
              description: URL de la glace créée
              schema:
                type: string
                format: uri
        '400':
          description: La glace n'a pas pu être créée/modifiée, il manque des champs obligatoires
        '422':
          description: La glace n'a pas pu être créée/modifiée, un champ est invalide
      deprecated: false
  /ice-creams/{id}:
    get:
      tags:
        - ice-creams
      summary: Obtient une glace
      operationId: getIceCream
      parameters:
        - name: id
          in: path
          description: numéro de la glace à obtenir
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/IceCreamDTOobj'
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - ice-creams
      summary: Supprimer une glace
      operationId: deleteIceCream
      parameters:
        - name: id
          in: path
          description: numéro de la glace à supprimer
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Glace supprimée
        '404':
          description: Not Found
      deprecated: false
  /origins:
    get:
      tags:
        - origins
      summary: Obtient une liste de toutes les origines possibles
      operationId: getOrigins
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OriginDTOobj'
  /containers:
    get:
      tags:
        - containers
      summary: Obtient une liste de toutes les containers pour les glaces
      operationId: getContainers
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContainerDTOobj'
components:
  schemas:
    IceCreamDTO:
      description: toutes les caractéristiques d'une glace
      type: object
      properties:
        id:
          description: numéro auto-incrémenté de la glace
          type: integer
          readOnly: true
        name:
          description: nom de la glace
          type: string
        price:
          description: prix de la glace
          type: number
          format: float
      required:
        - name
        - price
      title: IceCreamDTO
    IceCreamDTOid:
      allOf:
        - $ref: '#/components/schemas/IceCreamDTO'
        - type: object
          properties:
            originId:
              description: id de l'origine de la glace
              type: integer
            containerIds:
              description: liste des id des containers de la glace
              type: array
              items:
                type: integer
          required:
            - originId
            - containerIds
      title: IceCreamDTOid
    IceCreamDTOobj:
      allOf:
        - $ref: '#/components/schemas/IceCreamDTO'
        - type: object
          properties:
            origin:
              $ref: '#/components/schemas/OriginDTO'
            containers:
              type: array
              items:
                $ref: '#/components/schemas/ContainerDTO'
          required:
            - origin
            - containers
      title: IceCreamDTOobj
    OriginDTO:
      description: toutes les caractéristiques d'une origine
      type: object
      properties:
        id:
          description: numéro auto-incrémenté de l'origine
          type: integer
          readOnly: true
        name:
          description: nom du pays d'origine
          type: string
      required:
        - name
      title: OriginDTO
    OriginDTOid:
      allOf:
        - $ref: '#/components/schemas/OriginDTO'
        - type: object
          properties:
            iceCreamIds:
              description: Toutes les glaces venant de cette origine
              type: array
              items:
                type: integer
          required:
            - iceCreamIds
      title: OriginDTOid
    OriginDTOobj:
      allOf:
        - $ref: '#/components/schemas/OriginDTO'
        - type: object
          properties:
            iceCreams:
              type: array
              items:
                $ref: '#/components/schemas/IceCreamDTO'
          required:
            - iceCreams
      title: OriginDTOobj
    ContainerDTO:
      description: toutes les caractéristiques d'un container
      type: object
      properties:
        id:
          description: numéro auto-incrémenté du container
          type: integer
          readOnly: true
        name:
          description: nom du récipient dans lequelle la glace se trouve
          type: string
      required:
        - name
      title: ContainerDTO
    ContainerDTOid:
      allOf:
        - $ref: '#/components/schemas/ContainerDTO'
        - type: object
          properties:
            iceCreamIds:
              description: Toutes les glaces liées au container
              type: array
              items:
                type: integer
          required:
            - iceCreamIds
      title: ContainerDTOid
    ContainerDTOobj:
      allOf:
        - $ref: '#/components/schemas/ContainerDTO'
        - type: object
          properties:
            iceCreams:
              type: array
              items:
                $ref: '#/components/schemas/IceCreamDTO'
          required:
            - iceCreams
      title: ContainerDTOobj